In [1]:
import pandas as pd

### Description
- Notebook to analyse buidling information provided by Bag.
- Opensource dataset available on: https://data.nlextract.nl/bag/csv/bag-adressen-full-laatst.csv.zip
- Simple script that cleans data for simulation modelling

Author: M. Hupkens
<br>
Date: 26-03-2019

In [2]:
'''Data import'''

df = pd.read_csv("bagadres-full.csv", sep=';')

# show data
df.head()

C:\Users\markhupkens\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,openbareruimte,huisnummer,huisletter,huisnummertoevoeging,postcode,woonplaats,gemeente,provincie,nummeraanduiding,verblijfsobjectgebruiksdoel,...,object_id,object_type,nevenadres,pandid,pandstatus,pandbouwjaar,x,y,lon,lat
0,De Ruijterkade,105,NaN,1,1011AB,Amsterdam,Amsterdam,Noord-Holland,363200000081086,kantoorfunctie,...,363010000964973,VBO,f,3.631000e+14,Pand in gebruik,1884.0,122177.0,487877.0,4.905167,52.377780
1,De Ruijterkade,105,NaN,2,1011AB,Amsterdam,Amsterdam,Noord-Holland,363200000081087,woonfunctie,...,363010000784610,VBO,f,3.631000e+14,Pand in gebruik,1884.0,122177.0,487877.0,4.905167,52.377780
2,De Ruijterkade,105,NaN,3,1011AB,Amsterdam,Amsterdam,Noord-Holland,363200000081088,woonfunctie,...,363010000977861,VBO,f,3.631000e+14,Pand in gebruik,1884.0,122177.0,487877.0,4.905167,52.377780
3,De Ruijterkade,105,NaN,H,1011AB,Amsterdam,Amsterdam,Noord-Holland,363200000081085,bijeenkomstfunctie,...,363010000785105,VBO,f,3.631000e+14,Pand in gebruik,1884.0,122177.0,487877.0,4.905167,52.377780
4,De Ruijterkade,106,NaN,1,1011AB,Amsterdam,Amsterdam,Noord-Holland,363200012064203,kantoorfunctie,...,363010012064067,VBO,f,3.631000e+14,Pand in gebruik,1884.0,122185.0,487882.9,4.905284,52.377833

In [5]:
'''Select data'''

# select residential buildings
df2 = df[df['verblijfsobjectgebruiksdoel']=='woonfunctie'] 

# print unique records
print('Number of individual residential buildings in dataset =',len(df2)) 

# show unique records
df2.groupby(['woonplaats','openbareruimte']).count().sort_values(by='huisnummer', ascending=False).head()

Number of individual residential buildings in dataset = 7858625

,,huisnummer,huisletter,huisnummertoevoeging,postcode,gemeente,provincie,nummeraanduiding,verblijfsobjectgebruiksdoel,oppervlakteverblijfsobject,verblijfsobjectstatus,object_id,object_type,nevenadres,pandid,pandstatus,pandbouwjaar,x,y,lon,lat
woonplaats,openbareruimte,,,,,,,,,,,,,,,,,,,,
's-Gravenhage,Laan van Meerdervoort,2292,768,333,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292,2292
Amsterdam,Prinsengracht,2171,1196,795,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171
Nijmegen,Zwanenveld,2132,0,0,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132,2132
Zeist,Laan van Vollenhove,2089,7,97,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089
's-Gravenhage,Waldorpstraat,1933,990,448,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933

In [6]:
# show variables in dataset
df.columns

Index(['openbareruimte', 'huisnummer', 'huisletter', 'huisnummertoevoeging',
       'postcode', 'woonplaats', 'gemeente', 'provincie', 'nummeraanduiding',
       'verblijfsobjectgebruiksdoel', 'oppervlakteverblijfsobject',
       'verblijfsobjectstatus', 'object_id', 'object_type', 'nevenadres',
       'pandid', 'pandstatus', 'pandbouwjaar', 'x', 'y', 'lon', 'lat'],
      dtype='object')

In [7]:
df.verblijfsobjectstatus.unique()

array(['Verblijfsobject in gebruik', 'Verblijfsobject gevormd',
       'Plaats aangewezen', 'Verblijfsobject in gebruik (niet ingemeten)',
       'Verblijfsobject buiten gebruik'], dtype=object)

In [10]:
df.oppervlakteverblijfsobject.describe()

count    9.110822e+06
mean     1.804438e+02
std      1.763847e+03
min      0.000000e+00
25%      7.600000e+01
50%      1.050000e+02
75%      1.390000e+02
max      9.999990e+05
Name: oppervlakteverblijfsobject, dtype: float64

In [11]:
df.object_type.unique()

array(['VBO', 'LIG', 'STA'], dtype=object)